# Makes the media the core checks run against.
#
# Nothing here comes from outside: every file is generated by FFmpeg from
# synthetic sources, so the checks can run on a machine that has never seen a
# real recording — a build server, for instance.
#
#   powershell -File tools\make-test-media.ps1 -OutDir build\media
#
# Needs an ffmpeg.exe. By default it takes the one shipped in ffmpeg\bin, which
# is the same build the plug-in links against.

param(
    [string]$OutDir = "build\media",
    [string]$FFmpeg = "ffmpeg\bin\ffmpeg.exe"
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $FFmpeg)) {
    $fallback = (Get-Command ffmpeg -ErrorAction SilentlyContinue).Source
    if (-not $fallback) { throw "ffmpeg not found: neither $FFmpeg nor one on PATH" }
    $FFmpeg = $fallback
}

New-Item -ItemType Directory -Force $OutDir | Out-Null

function Make($name, $ffargs) {
    $path = Join-Path $OutDir $name
    if (Test-Path $path) { Write-Host "  have  $name"; return }
    Write-Host "  make  $name"
    # $args здесь нельзя: это встроенная переменная PowerShell, и своя
    # с таким именем молча не подставляется
    & $FFmpeg -y -hide_banner -loglevel error @ffargs $path
    if ($LASTEXITCODE -ne 0) { throw "ffmpeg failed on $name" }
}

Write-Host "test media in $OutDir"

# AV1, 8-bit, two separate audio tracks - the shape an OBS recording has
Make "av1_8bit.mp4" @(
    "-f","lavfi","-i","testsrc2=size=640x360:rate=60:duration=12",
    "-f","lavfi","-i","sine=frequency=440:duration=12",
    "-f","lavfi","-i","sine=frequency=880:duration=12",
    "-map","0:v","-map","1:a","-map","2:a",
    "-c:v","libsvtav1","-preset","12","-crf","50","-g","60","-c:a","aac")

# AV1, 10-bit, a gradient - banding shows up here if the depth is lost
Make "av1_10bit.mp4" @(
    "-f","lavfi","-i","gradients=size=640x360:rate=30:duration=8:c0=black:c1=white:type=linear",
    "-f","lavfi","-i","sine=frequency=440:duration=8",
    "-map","0:v","-map","1:a",
    "-pix_fmt","yuv420p10le","-c:v","libsvtav1","-preset","12","-crf","20","-g","30","-c:a","aac")

# VP9 in WebM with Opus - what footage from the web looks like
Make "vp9.webm" @(
    "-f","lavfi","-i","testsrc2=size=640x360:rate=30:duration=8",
    "-f","lavfi","-i","sine=frequency=440:duration=8:sample_rate=48000",
    "-map","0:v","-map","1:a",
    "-c:v","libvpx-vp9","-crf","50","-b:v","0","-speed","8","-row-mt","1",
    "-c:a","libopus","-ac","2")

# VP9 with transparency - the alpha lives beside the stream, not in it
Make "vp9_alpha.webm" @(
    "-f","lavfi","-i","testsrc2=size=320x180:rate=30:duration=6",
    "-f","lavfi","-i","gradients=size=320x180:rate=30:duration=6:c0=black:c1=white",
    "-filter_complex","[0:v][1:v]alphamerge,format=yuva420p[v]","-map","[v]",
    "-c:v","libvpx-vp9","-crf","50","-b:v","0","-speed","8","-auto-alt-ref","0")

# Audio with no video at all, in a container Premiere cannot open
Make "audio_only.mka" @(
    "-f","lavfi","-i","sine=frequency=440:duration=8:sample_rate=48000",
    "-f","lavfi","-i","sine=frequency=660:duration=8:sample_rate=48000",
    "-map","0:a","-map","1:a","-c:a","flac","-ac","2")

# The other side of the line: audio in MP4, which Premiere opens itself and the
# plug-in must refuse
Make "audio_only.mp4" @(
    "-f","lavfi","-i","sine=frequency=440:duration=4",
    "-c:a","aac")

# Variable frame rate: ten frames a second for the first half, sixty for the
# second. Nothing announces that in the header - Matroska still says 60 - so a
# plug-in that trusts the declared rate lines the picture up wrongly.
#
# Made by dropping five frames out of every six in the first half rather than by
# rewriting timestamps: that leaves the spacing genuinely uneven and the
# timestamps monotonic, the way a screen recorder produces it.
Make "vfr.mkv" @(
    "-f","lavfi","-i","testsrc2=size=320x180:rate=60:duration=10",
    "-f","lavfi","-i","sine=frequency=440:duration=10",
    "-filter_complex","[0:v]select='if(lt(n,300),not(mod(n,6)),1)'[v]",
    "-map","[v]","-map","1:a","-fps_mode:v","vfr",
    "-c:v","libsvtav1","-preset","12","-crf","50","-g","60","-c:a","aac")

# A flash in the picture and a click in the sound at exactly the same instant,
# two seconds in. Anything that shifts one against the other shows up as a
# distance between them - which is the only way to measure sync without eyes.
$syncArgs = @(
    "-f","lavfi","-i","color=c=black:s=320x180:r=30:d=6",
    "-f","lavfi","-i","sine=frequency=1000:duration=6",
    "-vf","drawbox=x=0:y=0:w=iw:h=ih:color=white:t=fill:enable='eq(n,60)'",
    "-af","volume=volume=0:enable='not(between(t,2,2.05))'",
    "-map","0:v","-map","1:a",
    "-c:v","libsvtav1","-preset","8","-crf","25","-g","30","-c:a","aac")

Make "sync.mp4" $syncArgs

# The same file, except both streams begin five seconds into the timeline
# instead of at zero. Recordings off a TS stream and anything muxed with
# -copyts look like this. The picture and the sound must still meet.
Make "sync_offset.mp4" ($syncArgs + @("-output_ts_offset","5.0"))

# A flat colour tagged BT.709, deliberately at a small frame size.
#
# The size is the point. Where a file says nothing about its colour, the frame
# height decides — under 576 lines means standard definition and BT.601. This
# file says BT.709 while being 180 lines tall, so anything that guesses instead
# of reading the tag gets it wrong, and the check below notices.
#
# SVT-AV1 does not write the colour description into the stream itself, only
# the container carries it — which is exactly the case that made the first
# attempt at this fix change nothing at all.
Make "colour_bt709.mp4" @(
    "-f","lavfi","-i","color=c=0xE04030:s=320x180:r=30:d=1",
    "-vf","format=yuv420p",
    "-colorspace","bt709","-color_primaries","bt709","-color_trc","bt709",
    "-color_range","tv",
    "-c:v","libsvtav1","-preset","6","-crf","8")

# HDR: BT.2020 primaries with the PQ transfer curve, 10-bit.
#
# In Matroska rather than MP4, and that is not a preference. Written straight
# to MP4, FFmpeg here keeps the matrix tag and drops the primaries and the
# transfer, which leaves a file that cannot test what it was made to test.
# Matroska carries all three, so the file is built and then remuxed.
Make "hdr_pq_temp.mp4" @(
    "-f","lavfi","-i","gradients=size=640x360:rate=30:duration=4:c0=black:c1=white:type=linear",
    "-f","lavfi","-i","sine=frequency=440:duration=4",
    "-map","0:v","-map","1:a","-pix_fmt","yuv420p10le",
    "-colorspace","bt2020nc","-color_primaries","bt2020","-color_trc","smpte2084",
    "-color_range","tv",
    "-c:v","libsvtav1","-preset","8","-crf","25","-g","30","-c:a","aac")

Make "hdr_pq.mkv" @(
    "-i",(Join-Path $OutDir "hdr_pq_temp.mp4"),"-c","copy",
    "-colorspace","bt2020nc","-color_primaries","bt2020","-color_trc","smpte2084",
    "-color_range","tv")

Remove-Item (Join-Path $OutDir "hdr_pq_temp.mp4") -ErrorAction SilentlyContinue

# H.264, the most ordinary file there is - must be handed back untouched.
# libopenh264 rather than libx264: the LGPL FFmpeg build has no x264 in it.
Make "h264.mp4" @(
    "-f","lavfi","-i","testsrc2=size=320x180:rate=30:duration=4",
    "-c:v","libopenh264","-b:v","300k","-pix_fmt","yuv420p")

Write-Host "done"
